service: food-advisor

plugins:
 - serverless-plugin-typescript
 - serverless-plugin-optimize
 - serverless-dynamodb-local
 - serverless-offline

provider:
 name: aws
 runtime: nodejs16.x
 environment:
  dynamodb_end_point: 'http://localhost:8000'
  COMMAND_ACCOUNT_TABLE: 'command_account'
  QUERY_ACCOUNT_TABLE: 'query_account'

custom:
  dynamodb:
    stages:
    # set for create tables on dev enviroment
      - dev
    start:
      inMemory: true
      port: 8000
      migrate: true # create tables on start
      onStart: true

resources: # CloudFormation template syntax
  Resources:
    commandAccountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: command_account
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: version
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    queryAccountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: query_account
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
 restaurant_module: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: ./src/lambda.handler
   events:
     - http:
        method: any
        path: /account/{any+}