service: food-advisor

plugins:
 - serverless-plugin-typescript
 - serverless-plugin-optimize
 - serverless-dynamodb-local
 - serverless-offline-dynamodb-streams
 - serverless-step-functions
 - '@fernthedev/serverless-offline-step-functions'
 - serverless-offline

provider:
 name: aws
 runtime: nodejs16.x
 environment:
  dynamodb_end_point: 'http://localhost:8000'
  COMMAND_ACCOUNT_TABLE: 'command_account'
  QUERY_ACCOUNT_TABLE: 'query_account'

custom:
  dynamodb:
    stages:
    # set for create tables on dev enviroment
      - dev
    start:
      inMemory: true
      port: 8000
      migrate: true # create tables on start
      onStart: true
  serverless-offline-dynamodb-streams: 
    endpoint: http://localhost:8000
  '@fernthedev/serverless-offline-step-functions':
    port: 8014
    enabled: true
    debug: true
resources: # CloudFormation template syntax
  Resources:
    commandAccountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: command_account
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: version
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamEnabled: true
          StreamViewType: NEW_AND_OLD_IMAGES
    queryAccountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: query_account
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  account_api: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: ./src/lambda.handler
   events:
     - http:
          method: ANY
          path: /
     - http:
          method: ANY
          path: '{proxy+}'
     - stream:
          type: dynamodb
          tableName: command_account
          batchSize: 100
          maximumRetryAttempts: 10
          startingPosition: LATEST
          arn: 
            Fn::GetAtt:
              - command_account
              - Arn
  # hello:
  #  handler: ./src/first-lambda.handler
  #  name: TheFirstLambda
  secondLambda:
   handler: ./src/second-lambda.secondhandler
  #  name: TheSecondLambda
stepFunctions:
  stateMachines:
    WaitMachine:
      definition:
        Comment: "An example of the Amazon States Language using wait states"
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource: !GetAtt account_api.Arn
              # Fn::GetAtt: 
              #   - hello
              #   - Arn
            Next: wait_using_seconds
          wait_using_seconds:
            Type: Wait
            Seconds: 10
            Next: FinalState
          FinalState:
            Type: Task
            Resource: 
              Fn::GetAtt: [account_api, Arn]
            End: true

